### ISSUE TITLE
Dynamic menu notification system

### ISSUE THREAD

**Issue by Helias** [UNICT-DMI/ERSU-Bot#14]
Create a settings system to all users that allow to choose which days and which meals get from the bot.

Example of interfaces (in buttons):

| Giorni    | Pranzo | Cena |
| --------- | ------ | ---- |
| Lunedì    | ✅     | ✅   |
| Martedì   | ✅     | ✅   |
| Mercoledì | ✅     | ✅   |
| Giovedì   | ✅     | ✅   |
| Venerdì   | ✅     | ✅   |
| Sabato    | ❌     | ❌   |
| Domenica  | ❌     | ❌   |

By clicking on ❌ it will switch to ✅ and vice versa.

In this case, the user will receive a notification for lunch and dinner (15 or 30 minutes before the open time) on all days except for Saturday and Sunday.

By default, this will be only lunch from Mon-Friday.

This task consists of:
- creating a database to save all the information per user
- creating a periodic job that checks the database and sends the notification to all users registered

This is a base, in the future we could add more features to this system.

**Comment by InfraBlue0** [comment]
How should I create a periodic job?

**Comment by marcospampi** [comment]
> How should I create a periodic job?

have a look here [https://github.com/UNICT-DMI/Telegram-DMI-Bot/blob/master/main.py](https://github.com/UNICT-DMI/Telegram-DMI-Bot/blob/master/main.py) and official [documentation.](https://docs.python-telegram-bot.org/en/stable/telegram.ext.jobqueue.html) 

The Telegram APIs expose their own methods to schedule job using their own event loop or job queue. Keep in mind that standard python has no concept of threads, instead you can achieve concurrent task execution using coroutines, or parallel execution via child processes.

@Helias did mentioned there are fine grained methods such as `run_daily`, so I suggest you to give a good read at that documentation.
